export const DEFAULT_PACKING = {
  "📄 Documents": [
    "Passport",
    "Visa / e-Visa",
    "Travel insurance",
    "Flight tickets",
    "Hotel bookings",
    "Emergency contacts",
  ],
  "👕 Clothing": [
    "T-shirts",
    "Pants / Jeans",
    "Underwear & socks",
    "Jacket / Coat",
    "Swimwear",
    "Walking shoes",
    "Sandals / Flip-flops",
  ],
  "🧴 Toiletries": [
    "Toothbrush & paste",
    "Shampoo & conditioner",
    "Sunscreen SPF 50+",
    "Deodorant",
    "Moisturiser",
    "Lip balm",
  ],
  "💊 Health": [
    "Prescription meds",
    "Painkillers",
    "Anti-diarrhoea tabs",
    "Hand sanitiser",
    "Face masks",
    "First aid kit",
  ],
  "🔌 Electronics": [
    "Phone charger",
    "Power bank",
    "Universal adapter",
    "Earphones",
    "Camera",
    "Laptop / Tablet",
  ],
  "🎒 Essentials": [
    "Cash (local currency)",
    "Credit / Debit cards",
    "Snacks",
    "Water bottle",
    "Travel pillow",
    "Luggage locks",
  ],
}
export const EXPENSE_CATS = [
  "🍜 Food & Drink",
  "🚌 Transport",
  "🏨 Accommodation",
  "🎡 Activities",
  "🛍️ Shopping",
  "💊 Health",
  "📱 Other",
]
export const CURRENCIES = [
  "USD",
  "SGD",
  "EUR",
  "GBP",
  "JPY",
  "AUD",
  "CNY",
  "CAD",
  "THB",
  "IDR",
  "MYR",
  "KRW",
  "HKD",
  "INR",
  "AED",
  "NZD",
  "CHF",
  "SEK",
  "NOK",
  "DKK",
  "TWD",
  "PHP",
  "VND",
  "PKR",
  "BDT",
  "LKR",
  "NPR",
  "MXN",
  "BRL",
  "ZAR",
  "TRY",
  "ILS",
  "QAR",
  "SAR",
  "KWD",
  "BHD",
  "OMR",
  "JOD",
  "EGP",
  "NGN",
  "KES",
  "GHS",
  "TZS",
  "UGX",
  "MAD",
  "TND",
  "DZD",
  "RUB",
  "UAH",
  "PLN",
  "CZK",
  "HUF",
  "RON",
  "BGN",
  "HRK",
  "RSD",
  "ISK",
  "ARS",
  "CLP",
  "COP",
  "PEN",
  "UYU",
  "VES",
]

// Country code (ISO 3166-1 alpha-2) → currency code (ISO 4217)
export const COUNTRY_CURRENCY = {
  AE: "AED",
  AF: "AFN",
  AL: "ALL",
  AM: "AMD",
  AO: "AOA",
  AR: "ARS",
  AT: "EUR",
  AU: "AUD",
  AZ: "AZN",
  BA: "BAM",
  BD: "BDT",
  BE: "EUR",
  BF: "XOF",
  BG: "BGN",
  BH: "BHD",
  BI: "BIF",
  BJ: "XOF",
  BN: "BND",
  BO: "BOB",
  BR: "BRL",
  BT: "BTN",
  BW: "BWP",
  BY: "BYN",
  BZ: "BZD",
  CA: "CAD",
  CD: "CDF",
  CF: "XAF",
  CG: "XAF",
  CH: "CHF",
  CI: "XOF",
  CL: "CLP",
  CM: "XAF",
  CN: "CNY",
  CO: "COP",
  CR: "CRC",
  CU: "CUP",
  CV: "CVE",
  CY: "EUR",
  CZ: "CZK",
  DE: "EUR",
  DJ: "DJF",
  DK: "DKK",
  DO: "DOP",
  DZ: "DZD",
  EC: "USD",
  EE: "EUR",
  EG: "EGP",
  ER: "ERN",
  ES: "EUR",
  ET: "ETB",
  FI: "EUR",
  FJ: "FJD",
  FR: "EUR",
  GA: "XAF",
  GB: "GBP",
  GE: "GEL",
  GH: "GHS",
  GM: "GMD",
  GN: "GNF",
  GQ: "XAF",
  GR: "EUR",
  GT: "GTQ",
  GW: "XOF",
  GY: "GYD",
  HK: "HKD",
  HN: "HNL",
  HR: "HRK",
  HT: "HTG",
  HU: "HUF",
  ID: "IDR",
  IE: "EUR",
  IL: "ILS",
  IN: "INR",
  IQ: "IQD",
  IR: "IRR",
  IS: "ISK",
  IT: "EUR",
  JM: "JMD",
  JO: "JOD",
  JP: "JPY",
  KE: "KES",
  KG: "KGS",
  KH: "KHR",
  KR: "KRW",
  KW: "KWD",
  KZ: "KZT",
  LA: "LAK",
  LB: "LBP",
  LI: "CHF",
  LK: "LKR",
  LR: "LRD",
  LS: "LSL",
  LT: "EUR",
  LU: "EUR",
  LV: "EUR",
  LY: "LYD",
  MA: "MAD",
  MC: "EUR",
  MD: "MDL",
  ME: "EUR",
  MG: "MGA",
  MK: "MKD",
  ML: "XOF",
  MM: "MMK",
  MN: "MNT",
  MO: "MOP",
  MR: "MRU",
  MT: "EUR",
  MU: "MUR",
  MV: "MVR",
  MW: "MWK",
  MX: "MXN",
  MY: "MYR",
  MZ: "MZN",
  NA: "NAD",
  NE: "XOF",
  NG: "NGN",
  NI: "NIO",
  NL: "EUR",
  NO: "NOK",
  NP: "NPR",
  NR: "AUD",
  NZ: "NZD",
  OM: "OMR",
  PA: "PAB",
  PE: "PEN",
  PG: "PGK",
  PH: "PHP",
  PK: "PKR",
  PL: "PLN",
  PT: "EUR",
  PW: "USD",
  PY: "PYG",
  QA: "QAR",
  RO: "RON",
  RS: "RSD",
  RU: "RUB",
  RW: "RWF",
  SA: "SAR",
  SC: "SCR",
  SD: "SDG",
  SE: "SEK",
  SG: "SGD",
  SI: "EUR",
  SK: "EUR",
  SL: "SLL",
  SM: "EUR",
  SN: "XOF",
  SO: "SOS",
  SR: "SRD",
  SS: "SSP",
  ST: "STN",
  SV: "USD",
  SY: "SYP",
  SZ: "SZL",
  TD: "XAF",
  TG: "XOF",
  TH: "THB",
  TJ: "TJS",
  TL: "USD",
  TM: "TMT",
  TN: "TND",
  TO: "TOP",
  TR: "TRY",
  TT: "TTD",
  TW: "TWD",
  TZ: "TZS",
  UA: "UAH",
  UG: "UGX",
  US: "USD",
  UY: "UYU",
  UZ: "UZS",
  VA: "EUR",
  VE: "VES",
  VN: "VND",
  VU: "VUV",
  WS: "WST",
  XK: "EUR",
  YE: "YER",
  ZA: "ZAR",
  ZM: "ZMW",
  ZW: "ZWL",
}

// Generate flag emoji from ISO 3166-1 alpha-2 country code
export const countryFlag = (cc) =>
  cc
    ? [...cc.toUpperCase()].map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397)).join("")
    : "🌍"

export const WC_ICON = (c) =>
  c === 0
    ? "☀️"
    : c <= 3
      ? "⛅"
      : c <= 48
        ? "🌫️"
        : c <= 67
          ? "🌧️"
          : c <= 77
            ? "❄️"
            : c <= 82
              ? "🌦️"
              : "⛈️"
export const WC_DESC = (c) =>
  c === 0
    ? "Clear sky"
    : c <= 3
      ? "Partly cloudy"
      : c <= 48
        ? "Foggy"
        : c <= 67
          ? "Rainy"
          : c <= 77
            ? "Snowy"
            : c <= 82
              ? "Light showers"
              : "Thunderstorm"
